### Import Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_excel('rev data for test.xlsx')

### Get familier with data

In [5]:
df.head()

              Type  Latitude  Longitude                        Report Location
0  Beaver Accident   47.6992  -122.2167  (47.6291923608656, -122.186728398282)
1  Beaver Accident   47.6977  -122.2164  (47.5576821104334, -122.156421437319)
2  Beaver Accident   47.6967  -122.2131  (47.6167258135906, -122.173139389518)
3  Beaver Accident   47.6971  -122.2178  (47.5370517340417, -122.197755316941)
4  Beaver Accident   47.6925  -122.2127   (47.6124577512516, -122.14272010056)

In [26]:
df.drop('Type',axis=1)

      Latitude   Longitude                        Report Location
0     47.69920 -122.216700  (47.6291923608656, -122.186728398282)
1     47.69770 -122.216400  (47.5576821104334, -122.156421437319)
2     47.69670 -122.213100  (47.6167258135906, -122.173139389518)
3     47.69710 -122.217800  (47.5370517340417, -122.197755316941)
4     47.69250 -122.212700   (47.6124577512516, -122.14272010056)
5     47.69870 -122.214300    (47.628665694003, -122.19427287398)
6     47.69350 -122.210200  (47.5635442513027, -122.140225918768)
7     47.63543 -122.238200  (47.5643422225133, -122.188209474359)
8     47.63552 -122.237400   (47.5452255162365, -122.16735161758)
9     47.63591 -122.231800  (47.6090516220791, -122.181793731417)
10    47.63591 -122.235900  (47.5390558115465, -122.155850906966)
11    47.63660 -122.240000  (47.6199779155653, -122.169989821207)
12    47.63420 -122.180100  (47.6042409259488, -122.180090164298)
13    47.62470 -122.196100  (47.6247019293543, -122.196054730371)
14    47.63950 -122.215190  (47.5949913762232, -122.151858143732)
15    47.62790 -122.239300  (47.5979194153391, -122.199296608055)
16    47.63830 -122.227300  (47.6082601542386, -122.187273044188)
17    47.63516 -122.227100   (47.561573023557, -122.157083748281)
18    47.63582 -122.238850  (47.5481709984225, -122.188469509748)
19    47.62503 -122.224900  (47.6102622506443, -122.144898800074)
20    47.57190 -122.233400  (47.5718548881898, -122.153412521121)
21    47.55140 -122.222100  (47.5513683240594, -122.172114016823)
22    47.55380 -122.214500  (47.5538454131583, -122.174504513319)
23    47.60280 -122.222700  (47.6027799017162, -122.142701553192)
24    47.54220 -122.231600  (47.5422322798575, -122.191576391564)
25    47.56960 -122.174800  (47.5695823278231, -122.174830998593)
26    47.59700 -122.205000  (47.6125859417606, -122.187761484809)
27    47.59720 -122.207000  (47.5831576151833, -122.161116629167)
28    47.59900 -122.210000  (47.6237728247834, -122.155977795137)
29    47.59340 -122.206000  (47.5534396899435, -122.162908032058)
...        ...         ...                                    ...
1484  47.59000 -122.361612  (47.5872326579041, -122.384938760246)
1485  47.58390 -122.402230   (47.578485093726, -122.366379954451)
1486  47.58710 -122.425967  (47.5795543827194, -122.398954143703)
1487  47.59000 -122.367611  (47.5940766033066, -122.371261191829)
1488  47.60000 -122.364152  (47.5988744504573, -122.350278711369)
1489  47.60000 -122.375014  (47.5994946914629, -122.393501906216)
1490  47.60000 -122.351948  (47.5977135390967, -122.356108628629)
1491  47.58605 -122.438626  (47.5813951032773, -122.360243087513)
1492  47.61000 -122.352094  (47.6072344567457, -122.389965082195)
1493  47.59000 -122.365561   (47.585170447005, -122.364624525827)
1494  47.60000 -122.363258  (47.5952760116857, -122.375355045877)
1495  47.60000 -122.361581  (47.5986602893748, -122.373583221944)
1496  47.61070 -122.371647  (47.5746098786711, -122.369437532685)
1497  47.60000 -122.363726  (47.6012490171942, -122.355327791053)
1498  47.60000 -122.365538  (47.5989348567915, -122.386267563737)
1499  47.58710 -122.444270  (47.5815237704914, -122.372063895927)
1500  47.58770 -122.418635  (47.5763326667125, -122.394634816053)
1501  47.60000 -122.379463  (47.6012491117075, -122.352494446061)
1502  47.60000 -122.353422  (47.5964094820512, -122.374547856058)
1503  47.60000 -122.353942  (47.6027390854318, -122.384886359999)
1504  47.61000 -122.373075  (47.6098121652091, -122.351614659555)
1505  47.60022 -122.370424  (47.5710850474414, -122.364325503371)
1506  47.61000 -122.358565  (47.6087206284334, -122.376515345128)
1507  47.60000 -122.357687  (47.6005478556593, -122.384348533395)
1508  47.58780 -122.411625   (47.5763082020331, -122.36812137844)
1509  47.58910 -122.421900  (47.5803949885849, -122.359859424757)
1510  47.59000 -122.376495  (47.5890338500093, -122.378018007636)
1511  47.61280 -122.373211  (47.5728901259995, -122.355987096882)
1512  47.61000 -122.361927   (47.608958904841, -122.388274687981)
1513  47.60000 -122.350487  (47.6041100663205, -122.377337083509)

[1514 rows x 3 columns]

In [28]:
df[['Latitude','Longitude']]

      Latitude   Longitude
0     47.69920 -122.216700
1     47.69770 -122.216400
2     47.69670 -122.213100
3     47.69710 -122.217800
4     47.69250 -122.212700
5     47.69870 -122.214300
6     47.69350 -122.210200
7     47.63543 -122.238200
8     47.63552 -122.237400
9     47.63591 -122.231800
10    47.63591 -122.235900
11    47.63660 -122.240000
12    47.63420 -122.180100
13    47.62470 -122.196100
14    47.63950 -122.215190
15    47.62790 -122.239300
16    47.63830 -122.227300
17    47.63516 -122.227100
18    47.63582 -122.238850
19    47.62503 -122.224900
20    47.57190 -122.233400
21    47.55140 -122.222100
22    47.55380 -122.214500
23    47.60280 -122.222700
24    47.54220 -122.231600
25    47.56960 -122.174800
26    47.59700 -122.205000
27    47.59720 -122.207000
28    47.59900 -122.210000
29    47.59340 -122.206000
...        ...         ...
1484  47.59000 -122.361612
1485  47.58390 -122.402230
1486  47.58710 -122.425967
1487  47.59000 -122.367611
1488  47.60000 -122.364152
1489  47.60000 -122.375014
1490  47.60000 -122.351948
1491  47.58605 -122.438626
1492  47.61000 -122.352094
1493  47.59000 -122.365561
1494  47.60000 -122.363258
1495  47.60000 -122.361581
1496  47.61070 -122.371647
1497  47.60000 -122.363726
1498  47.60000 -122.365538
1499  47.58710 -122.444270
1500  47.58770 -122.418635
1501  47.60000 -122.379463
1502  47.60000 -122.353422
1503  47.60000 -122.353942
1504  47.61000 -122.373075
1505  47.60022 -122.370424
1506  47.61000 -122.358565
1507  47.60000 -122.357687
1508  47.58780 -122.411625
1509  47.58910 -122.421900
1510  47.59000 -122.376495
1511  47.61280 -122.373211
1512  47.61000 -122.361927
1513  47.60000 -122.350487

[1514 rows x 2 columns]

## K-means Clustering

In [1]:
from sklearn.cluster import KMeans

In [23]:
kmeans = KMeans(n_clusters=3)

In [29]:
kmeans.fit(df[['Latitude','Longitude']])

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [30]:
kmeans.cluster_centers_
kmeans.labels_

array([[  47.58474268, -122.17208312],
       [  47.59257705, -122.35403834],
       [  47.68369382, -122.32643645]])

array([2, 2, 2, ..., 1, 1, 1])